version: "3.9"
services:
  backend:
    build:
      context: ./airlines-search-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
  frontend:
    build:
      context: ./airlines-search-frontend
    ports:
      - "80:80"
